import {Input,Output,Conversion,ALL_FORMATS,BlobSource,BufferTarget,Mp4OutputFormat,Quality} from "https://cdn.jsdelivr.net/npm/mediabunny/+esm";
const $=s=>document.querySelector(s);let file=null,result=null,resultName="";const W=3840,H=2160,FPS=60,BR=57300000,CODEC="avc1.640034";
function size(n){if(!n)return"—";if(n>1e9)return(n/1e9).toFixed(2)+" GB";if(n>1e6)return(n/1e6).toFixed(2)+" MB";return(n/1024).toFixed(1)+" KB"}function progress(p,t){$("#bar").style.width=p+"%";$("#pct").textContent=p+"%";$("#status").textContent=t}
$("#drop").onclick=()=>$("#file").click();$("#file").onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith("video/")&&!/\.(mp4|mov)$/i.test(f.name))return alert("Please choose an MP4 or MOV video.");file=f;$("#name").textContent="✓ "+f.name+" · "+size(f.size);$("#process").disabled=false;$("#process").textContent="PROCESS 4K60 H.264";progress(0,"Ready")};
async function detect(){if(!("VideoEncoder"in window)){$("#engine").textContent="❌ WebCodecs VideoEncoder is unavailable.";$("#engine").className="engine warn";return false}try{const r=await VideoEncoder.isConfigSupported({codec:CODEC,width:W,height:H,bitrate:BR,framerate:FPS,bitrateMode:"constant",hardwareAcceleration:"prefer-hardware",latencyMode:"quality"});if(r.supported){$("#engine").textContent="✓ H.264 4K60 supported · hardware-first";$("#engine").className="engine ok";return true}}catch(e){console.warn(e)}$("#engine").textContent="⚠ This device/browser does not report H.264 4K60 support.";$("#engine").className="engine warn";return false}detect();
async function encode(){progress(3,"Checking Android encoder…");if(!(await detect()))throw Error("This browser/device does not report H.264 3840×2160 60 FPS support.");progress(6,"Opening video locally…");const input=new Input({formats:ALL_FORMATS,source:new BlobSource(file)}),output=new Output({format:new Mp4OutputFormat({fastStart:"in-memory"}),target:new BufferTarget()});const c=await Conversion.init({input,output,tracks:"primary",video:{width:W,height:H,fit:"fill",frameRate:FPS,codec:"avc",quality:new Quality({bitrate:BR,bitrateMode:"constant"}),keyFrameInterval:2,hardwareAcceleration:"prefer-hardware",latencyMode:"quality",fullCodecString:CODEC,forceTranscode:true},audio:{codec:"aac",bitrate:192000,sampleRate:48000},tags:{}});if(!c.isValid)throw Error("Local conversion pipeline rejected this source.");c.onProgress=p=>progress(8+Math.round(p*90),"Encoding locally · H.264 4K60…");await c.execute();if(!output.target.buffer)throw Error("No MP4 output was produced.");result=new Blob([output.target.buffer],{type:"video/mp4"});resultName=file.name.replace(/\.[^.]+$/i,"")+"_dystore_v10.03_4k60.mp4";progress(100,"Complete ✓")}
async function inspect(blob){const u=URL.createObjectURL(blob),v=document.createElement("video");v.preload="metadata";v.src=u;const m=await new Promise(r=>{v.onloadedmetadata=()=>r([v.videoWidth,v.videoHeight,v.duration]);v.onerror=()=>r([0,0,0])});URL.revokeObjectURL(u);$("#res").textContent=m[0]?m[0]+" × "+m[1]:"—";$("#fps").textContent="60 FPS target";$("#bitrate").textContent=m[2]?(blob.size*8/m[2]/1e6).toFixed(2)+" Mbps":"—";$("#size").textContent=size(blob.size);$("#codec").textContent="H.264 / AVC";$("#profile").textContent="Client · HW-first";$("#notice").textContent="Measured from the generated MP4. prefer-hardware was requested; the browser may still choose software."}
$("#process").onclick=async()=>{if(!file)return;$("#process").disabled=true;$("#download").hidden=true;try{await encode();await inspect(result);$("#download").hidden=false;$("#process").disabled=false;$("#process").textContent="PROCESS AGAIN"}catch(e){console.error(e);progress(0,"Processing failed");alert(e?.message||"Processing failed");$("#process").disabled=false;$("#process").textContent="TRY AGAIN"}};
$("#download").onclick=()=>{if(!result)return;const u=URL.createObjectURL(result),a=document.createElement("a");a.href=u;a.download=resultName;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)};
