const file=document.querySelector("#file"),drop=document.querySelector("#drop"),fileName=document.querySelector("#fileName"),patch=document.querySelector("#patch"),progress=document.querySelector(".progress"),bar=document.querySelector(".progress i"),toast=document.querySelector("#toast"),historyList=document.querySelector("#historyList"),resolution=document.querySelector("#resolution"),fps=document.querySelector("#fps"),duration=document.querySelector("#duration"),size=document.querySelector("#size"),format=document.querySelector("#format");
let selected=null;
function notify(t){toast.textContent=t;toast.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove("show"),2200)}
function pick(f){if(!f)return;if(!/\.(mp4|mov)$/i.test(f.name)&&!f.type.startsWith("video/"))return notify("Please choose an MP4 or MOV video.");selected=f;fileName.textContent="✓ "+f.name;fileName.style.color="#24d9ff";patch.disabled=false;patch.textContent="START PATCH";inspectLocal(f)}
file.addEventListener("change",e=>pick(e.target.files[0]));
["dragenter","dragover"].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.style.borderColor="#bd5cff"}));
["dragleave","drop"].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.style.borderColor=""}));
drop.addEventListener("drop",e=>pick(e.dataTransfer.files[0]));
function inspectLocal(f){const v=document.createElement("video");v.preload="metadata";v.onloadedmetadata=()=>{resolution.textContent=v.videoWidth+" × "+v.videoHeight;duration.textContent=v.duration.toFixed(2)+"s";fps.textContent="Auto";size.textContent=(f.size/1048576).toFixed(2)+" MB";format.textContent=f.type||"video"};v.src=URL.createObjectURL(f)}
patch.addEventListener("click",()=>{if(!selected)return;patch.disabled=true;patch.textContent="PATCHING…";progress.style.display="block";let n=0;const timer=setInterval(()=>{n+=5;bar.style.width=n+"%";if(n>=100){clearInterval(timer);patch.disabled=false;patch.textContent="DOWNLOAD / SAVE";addHistory(selected.name);notify("Patch process finished.");}},80)});
function addHistory(name){if(historyList.classList.contains("empty"))historyList.classList.remove("empty"),historyList.innerHTML="";const row=document.createElement("div");row.style.cssText="display:flex;justify-content:space-between;padding:12px;border-bottom:1px solid #281332;font-size:9px";row.innerHTML=`<span>✓ ${name}</span><span style="color:#6fdfae">Completed</span>`;historyList.prepend(row)}
document.querySelector("#inspect").onclick=()=>{const u=document.querySelector("#tiktokUrl").value.trim();notify(u?"URL received — connect your TikTok API/inspector here.":"Select a video to inspect local metadata.")};
document.querySelector("#userBtn").onclick=()=>notify("dystore · FREE account");
